;; Exercise 3.4

(define (make-account balance password)
  (let ((count 0) (tolerance 7))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    (define (incorrect-password amount)
      (set! count (1+ count))
      (if (> count tolerance)
          (call-the-cops)
          "Incorrect password"))
    (define (password-check p m)
      (if (eq? p password)
          (begin (set! count 0)
                 (dispatch m))
          incorrect-password))
    password-check))
