;; Exercise 3.7

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((passwords (list password)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'new-password) new-password)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    (define (incorrect-password amount)
      "Incorrect password")
    (define (new-password p)
      (set! passwords (cons p passwords))
      password-check)
    (define (password-check p m)
      (if (member p passwords)
          (dispatch m)
          incorrect-password))
    password-check))

(define (make-joint acc old-pwd new-pwd)
  ((acc old-pwd 'new-password) new-pwd))
